#!/bin/bash
#SBATCH --job-name="N1 ref"
#SBATCH --output="N1.ref.%j.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
#SBATCH --mem=64G
#SBATCH --account=csd720
# #SBATCH --export=None
#SBATCH --export=ALL
#SBATCH -t 0:05:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=wezhan@ucsd.edu

export SLURM_EXPORT_ENV=ALL
module purge
module load cpu
#Load module file(s) into the shell environment
module load gcc/9.2.0
module load mvapich2/2.3.6
module load slurm

srun --mpi=pmi2 -n 16 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 16 -y 1
srun --mpi=pmi2 -n 16 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 8 -y 2
srun --mpi=pmi2 -n 16 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 4 -y 4
srun --mpi=pmi2 -n 16 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 2 -y 8
srun --mpi=pmi2 -n 16 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 1 -y 16

srun --mpi=pmi2 -n 32 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 32 -y 1
srun --mpi=pmi2 -n 32 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 8 -y 4
srun --mpi=pmi2 -n 32 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 4 -y 8
srun --mpi=pmi2 -n 32 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 1 -y 32

srun --mpi=pmi2 -n 64 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 16 -y 4
srun --mpi=pmi2 -n 64 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 8 -y 8
srun --mpi=pmi2 -n 64 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 4 -y 16

srun --mpi=pmi2 -n 128 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 64 -y 2
srun --mpi=pmi2 -n 128 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 16 -y 8
srun --mpi=pmi2 -n 128 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 8 -y 16
srun --mpi=pmi2 -n 128 $PUB/HW/hw3/apf-ref -n 1800 -i 100000 -x 2 -y 64
